apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: fintech-worker-scaler
  namespace: fintech-prod
spec:
  scaleTargetRef:
    name: fintech-worker
  triggers:
  - type: aws-sqs-queue
    metadata:
      queueURL: https://sqs.us-east-1.amazonaws.com/797923187401/fintech-queue
      awsRegion: us-east-1
      identityOwner: operator
    authenticationRef:
      name: aws-credentials